[toolchain]

[programs.testnet]
character = "HxkYZ6hAFhVpjEMtLDfYwDmMUCu5ctzB4hLG2bjCH1sB"
room = "8eoFAxiRrAh5RPPuDNyJT6CdJRQLHbs2ntzJRHZ2dsfb"
attack = "71PwZ3SAgUPY6jDZYMLRNJsAh98Pz48EWq6pAHsLtF6i"
block_attack = "J3ShPaMqkkSexm6HRMSx3DFD8yx5ZDK9HApanQ9ypCwk"
create_room = "5unwDiZx5CesRy4BW42jFyBAeg3qqSAk3R2vNgsg83se"
move_character = "Emr1nmjo96yEHNJrcFCF6eEhddhvsdY2woNTJFZMEBkU"
spawn = "G7nyjrAKgXJup6aGfi4Zh5RSgwi6nTVTWfxRH7q6p178"
switch_attack_type = "4vQKQW8wVAEFQrMmAb5mDPkzMzpRLywc15gWJWgNDgKi"

[features]
resolution = true
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
